# Generated by Django 4.2.6 on 2023-10-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
